### PR TITLE
fixes #9622, add preprocessContent hook

### PR DESCRIPTION
**Pull request by dylans**

### CODE REVIEW

**Comment by dylans** [comment]
Updated PR to add tests, change onPreprocessContent to preprocessContent

**Comment by wkeese** [comment]
Does this test run for you?

**Comment by dylans** [comment]
I was unable to get doh robot to run locally, so I was hoping you could review and confirm the testcase that I created. If there's an issue with it, please let me know and I'll spend more time trying to get doh running.

**Comment by wkeese** [comment]
This test doesn't even use DOH robot, so that shouldn't be a problem.  Currently, the test file has a syntax error and doesn't even load.

**Comment by dylans** [comment]
Sorry, fixed that @wkeese ... note that this test seems to have a side effect on another test ( "ContentPane in StackContainer")... given the comment in it that it should have been removed after issue 3504 was fixed, perhaps its time to remove that test?

**Comment by wkeese** [comment]
Thanks, that's working much better.  The test looks good to me.

I don't understand what you mean about a side effect on the "ContentPane in StackContainer" test.  That test is still passing for me on Chrome/mac and also IE10.  What are you seeing?

**Comment by dylans** [comment]
I was seeing an error in the count of the number of items in the StackContainer, but it's possible something was wrong with my test environment. Let me know if you want me to land it (I can do it in the morning), or if you want to.

**Comment by wkeese** [comment]
OK thanks, I'm not seeing that error, so I pushed your change as 5c2ae92d056514463b6f49122e523712edc6eb10.

**Pull request closed without merging**
