### PR TITLE
fixes #16942, InlineEditBox does not mask password

### PR DESCRIPTION
**Pull request by dylans**

### CODE REVIEW

**Comment by wkeese** [comment]
I guess it's fine except that (as usual) it needs a test.

**Comment by Tomdye** [comment]
What about adding as many `*` as there are chars in the val?

**Comment by dylans** [comment]
@Tomdye I think there's generally mixed feelings on whether or not to make it match the password length, or just show an arbitrary length. Some argue that it's more secure to not show the actual length, whereas others argue that it confuses users if they don't know the length of the password they entered.

**Comment by Tomdye** [comment]
Guess it's a difficult one

**Comment by msssk** [comment]
Addressed in #126 (with test)

**Pull request closed without merging**
