### PR TITLE
Albanian language support

### PR DESCRIPTION
**Pull request by bucibucii**

### CODE REVIEW

**Comment by bucibucii** [comment]
Hi @dylans.
Did you merge my updates?
I didn't see them when i downloaded from https://dojotoolkit.org/download/

**Comment by bucibucii** [comment]
Soon i will upload dojo/dojo albanian nls folder!

**Comment by dylans** [comment]
Sorry not yet, should get to it this weekend.

**Comment by dylans** [comment]
@wkeese @bucibucii PR added at https://github.com/dojo/dijit/pull/166

**Pull request merged**
