### PR TITLE
Resolve iOS8 bug where keystrokes issue on 1.8 branch

### PR DESCRIPTION
**Pull request by nicknisi**
This issue was resolved in #82 and applied to master in 054073823470949ace3003f20fdb66ea5e470670. This commit applies the fix to the 1.8 branch.

### CODE REVIEW

**Comment by wkeese** [comment]
As I wrote in https://bugs.dojotoolkit.org/ticket/18396:

> Initially just checking code into master branch (for 1.11). The fix is non-trivial, so before backporting (if we want to backport), some other people should also check that the fix doesn't break anything.
comment:5

So, I guess you tested this and it's working for you?

**Comment by wkeese** [comment]
PS: Actually, this doesn't work at all.  It's referencing `has()` but `has()` isn't defined.

Also, the proper way to do backports like this is to call:

```
$ git cherry-pick -x  0540738
```

That way the original history and comment are preserved.

**Comment by dylans** [comment]
I don't think Nick can easily cherry-pick since he doesn't have commit privs for Dojo (though we should probably nominate him as a committer soon given his recent set of contributions). I guess he could have cherry-picked on his branch maybe

**Comment by nicknisi** [comment]
Whoops, I had that fixed locally, but I must not have committed before I pushed. Sorry about that.

I also had tried `git cherry-pick -x 0540738` but I had some issues, which I may now blame on the gui merge tool I was trying out because it was much simpler to resolve the conflicts from the command line this time around. I have updated this pull request to contain the cherry-picked commit instead.

Finally, thank you for pointing out the comment in the Dojo bug system. I overlooked that comment when looking to resolve this issue, but had found the original pull request. I was able to pretty easily reproduce the placeHolder bug on the 1.8 branch before applying this commit, and I have not been able to after applying the commit. I've worked with a couple of different projects using older versions of Dojo who have run into iOS8 issues like this and so I would definitely like to see it get backported. I'd be happy to help, too.

**Comment by wkeese** [comment]
OK great!  I will push the backports.  Also I'll push the cherry-pick to 1.10 and 1.9, since our policy is to always backport in reverse order.  1.10 and 1.9 don't have any conflicts so they are easy.

**Comment by wkeese** [comment]
FYI, I'm in the process of backporting this, starting with 1.10, but I'm hitting a failing in the 1.10 regression in test_Select.html?mode=test.   Probably unrelated, but I need to resolve that first.   Then move on to 1.9 and then 1.8.

**Pull request merged**
