### PR TITLE
Fixes #18888: BackgroundIframe not enabled for IE11/Win10

### PR DESCRIPTION
**Pull request by vansimke**
Updated user agent testing to determine if BackgroundIFrame is required to work for Windows 8, 8.1 and 10.

### CODE REVIEW

**Comment by wkeese** [comment]
Is this really for https://bugs.dojotoolkit.org/ticket/1888?  I guess you mean https://bugs.dojotoolkit.org/ticket/18888.

What if the check was just simplified to has("trident")?  I don't understand which case we are trying to avoid setting up the BackgroundIframe.   I guess for Windows Phone?

Also, the comment (from lines 15-21) needs to be updated too.

**Comment by vansimke** [comment]
You are correct. The actual issue being targeted is 18888. Further, I think that you have raised a valid point regarding which versions of Windows are being blocked out here. I didn't perform regression testing on older versions of Windows, so I don't know if implementing this on Windows 5.2 (XP) or before would cause unexpected behaviors, so I just added on the newer versions that weren't covered.

Also, I updated the comment as you mentioned.

**Comment by wkeese** [comment]
IE11 doesn't run on Windows XP or earlier, so isn't saying that the iframe is "enabled for IE11 on Windows 7, 8, 8.1, 10" the same thing as saying that it's enabled on IE11 anywhere?

**Comment by vansimke** [comment]
I wonder if we should just update the test to look for has('trident') === 7. That is IE11's version of Trident and would cover all places where its used regardless of OS. The concern I have with just using has('trident') is that it would capture IE all the way back to IE8. Does anyone have a concern with that?

**Comment by wkeese** [comment]
has('trident') === 7 seems better than the current patch, although since (a few years ago) we dropped support for IE6 and IE7 and think the current code could be further reduced to:

```js
has.add("config-bgIframe",
	has("trident") && !/IEMobile\/10\.0/.test(navigator.userAgent)); // No iframe on WP8, to match 1.9 behavior
```

If you're unconfortable breaking IE6 and IE7, even though we officially dropped support, then:

```js
has.add("config-bgIframe",
	(has("ie") || has("trident")) && !/IEMobile\/10\.0/.test(navigator.userAgent)); // No iframe on WP8, to match 1.9 behavior
```

**Comment by vansimke** [comment]
I've add a new commit that uses @wkeese's second check so that we don't break old IE unnecessarily.

**Comment by wkeese** [comment]
Looks good to me.

**Comment by vansimke** [comment]
Closed via https://github.com/dojo/dijit/commit/c07a4cd00fe7d5f3d5f475fe4222693d2d71a5c3. Backported as https://github.com/dojo/dijit/commit/68a5c5023fcaeaf0e4e3990a2d8a14232c6a9403 (1.11), https://github.com/dojo/dijit/commit/9dcc39aafe926f463529063694f6db86b0f989bd (1.10)

**Pull request closed without merging**
