### PR TITLE
toggleClass attribute mapping support, fixes #18435.

### PR DESCRIPTION
**Pull request by asudoh**

### CODE REVIEW

**Comment by wkeese** [comment]
Looks good to me.   I guess it should be documented in _WidgetBase.js (around line 108, where the other property --> DOM mapping stuff is documented).

**Comment by dylans** [comment]
Just curious, why the name "teeny"... is this a naming convention that already exists? It's not clear to me what it's supposed to describe.

**Comment by neonstalwart** [comment]
@dylans `teeny` is a property in the test widget that represents a class to be toggled based on the value of that property.

**Comment by dylans** [comment]
@neonstalwart thanks, sorry, missed the word test in the file path.

**Comment by asudoh** [comment]
@wkeese @dylans Thank you for reviewing. Created a new commit with in-line documentation.

**Comment by asudoh** [comment]
Thanks @wkeese!

**Pull request merged**
