### PR TITLE
fix for Tree node rename when textDir is "auto", and test

### PR DESCRIPTION
**Pull request by hhelena**
Added "apply text direction" on Node when the label is set, since if the old label was English and a new is Hebrew, text direction should be updated to RTL.

### CODE REVIEW

**Comment by wkeese** [comment]
Thanks for the PR, I will add comments inline.

**Comment by wkeese** [comment]
> Hi Bill, thank you very much for comments. In Tree.js I removed additional definition for _setLabelAttr() and added code to existing. I added automated test for "rename" to ProgrammaticTree.html and removed Tree_node_rename.html, that is not needed now. I commited and pushed the code. Please take a look. Thanks

OK, that's starting to look better.   But you still have the .project file in your patch.  That should be removed, right?   Also, you did *not* remove tests/_BidiSupport/tree/Tree_node_rename.html.  It's still listed in https://github.com/dojo/dijit/pull/87/files.

**Comment by hhelena** [comment]
Thanks for comments, I fixed input tag syntax and submitted Tree_node_rename.html and .project as "removed".

**Comment by wkeese** [comment]
OK thanks, that looks better.   Unfortunately I just noticed that you made this PR against 1.10.  PR's need to be made against the master branch.   This PR doesn't apply correctly against the master branch.  Actually, it doesn't even apply cleanly against the latest 1.10 branch.  So please submit a new PR (with your latest code) against the master branch.

**Comment by hhelena** [comment]
I committed against master. Thank you.

**Comment by wkeese** [comment]
OK, please submit a new PR.

**Pull request closed without merging**
