### PR TITLE
added 'aria-label' to each gridCell in dijit/CalendarLite

### PR DESCRIPTION
**Pull request by vansimke**

### CODE REVIEW

**Comment by wkeese** [comment]
Hmm.  So, the question here is what aria-label makes sense.  I thought the aria-label should be the whole date (ex: "September 5, 2000") whereas IIUC you are just setting it to "5".  But maybe just "5" is better.  It depends on if the "September 2000" part is already available to the screen reader via attributes (summary, aria-label, aria-labelledby, etc.) on the table itself.

**Comment by vansimke** [comment]
I thought about raising that question too, but I decided to get the ball rolling with a PR. I haven't worked with screen readers that much, so I don't know what the user would expect to happen. I'll Google around a bit and see if I can find any kind of consensus.

**Comment by Kagetsume** [comment]
For what it is worth, in my experience with screen readers, it would be
better to have the label set to the entire date so that it is fully
announced each tab/time.

**Comment by vansimke** [comment]
I couldn't find anything definitive. The closest I got was basically "make the label clear". So, after playing with it using a a screen reader extension, I've changed the implementation to use the long date format instead of just the number. Its a bit redundant when selecting the the the first time (the month is read twice), but when navigating around the cell, it seemed better to have the full date read out.

**Comment by wkeese** [comment]
👍

**Comment by vansimke** [comment]
@wkeese Are you okay with me merging this in then?

**Comment by wkeese** [comment]
Yup, that's what I was going for with the 👍.

**Comment by vansimke** [comment]
I figured, just wanted to be clear. I'll land it shortly.

**Comment by vansimke** [comment]
Closed via https://github.com/dojo/dijit/commit/959a8a2672169d5c1ce525fcdd5c8fc092abac2a

**Pull request closed without merging**
